#!/usr/bin/env bash

action=

case $1 in
    install)
        action=install
        ;;
    update)
        action=update
        ;;
    *)
        echo "Usage: $0 {install|update}"
        exit 255
        ;;
esac

function install() {
  go mod tidy || exit 255
}

function update() {
  go get -u -v ./... || exit 255
  go mod download || exit 255
}

for pkg in $(find . -name 'go.mod' -exec dirname {} \; | sort -u); do
    pushd "$pkg" > /dev/null 2>&1 || exit 255
    $action
    popd > /dev/null 2>&1 || exit 255
done
