name: Run Style Check And Unit Test

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.20

      - name: Set up tools
        run: |
          sudo apt update && sudo apt install -y build-essential bc

      - name: Install revive
        run: |
          go install github.com/mgechev/revive@latest

      - name: Style Check
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          # get all the changed directories
          changed_dirs=$(echo "$ALL_CHANGED_FILES" | tr ' ' '\n' | xargs -I {} dirname {} | sort -u | uniq)
          # get all changed packages
          changed_pkgs=()
          for dir in $changed_dirs; do
              # check if the dir has go.mod in it, recursively
              updated_dirs=$(find "$dir" -name 'go.mod' -exec dirname {} \; | sort -u | uniq)
              for updated_dir in $updated_dirs; do
                  changed_pkgs+=("$updated_dir")
              done
          done
          # unique the changed packages
          IFS=" " read -r -a changed_pkgs <<<"$(tr ' ' '\n' <<<"${changed_pkgs[@]}" | sort -u | tr '\n' ' ')"

          revive_config=$(realpath revive.toml)
          for pkg in "${changed_pkgs[@]}"; do
              # check do we need to run revive, include go files
              have_go_files=$(find "$pkg" -name '*.go' -maxdepth 1 -exec dirname {} \; | sort -u | uniq)
              if [ -z "$have_go_files" ]; then
                  continue
              fi
              echo "running go vet and revive for $pkg"
              pushd "$pkg" >/dev/null 2>&1 || exit 255
              go vet ./... || exit 255
              revive -formatter friendly -config $revive_config ./... || exit 255
              popd >/dev/null 2>&1 || exit 255
          done

      - name: Run Unit Test
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          # get all the changed directories
          changed_dirs=$(echo "$ALL_CHANGED_FILES" | tr ' ' '\n' | xargs -I {} dirname {} | sort -u | uniq)
          # get all changed packages
          changed_pkgs=()
          for dir in $changed_dirs; do
              # check if the dir has go.sum in it, recursively
              updated_dirs=$(find "$dir" -name 'go.sum' -exec dirname {} \; | sort -u | uniq)
              for updated_dir in $updated_dirs; do
                  changed_pkgs+=("$updated_dir")
              done
          done
          # unique the changed packages
          IFS=" " read -r -a changed_pkgs <<<"$(tr ' ' '\n' <<<"${changed_pkgs[@]}" | sort -u | tr '\n' ' ')"

          for pkg in "${changed_pkgs[@]}"; do
              # check do we need to run revive, include _test.go files
              have_go_files=$(find "$pkg" -name '*_test.go' -maxdepth 1 -exec dirname {} \; | sort -u | uniq)
              if [ -z "$have_go_files" ]; then
                  echo "skipping empty $pkg"
                  continue
              fi
              echo "running go test for $pkg"
              pushd > /dev/null 2>&1 "$pkg" || exit 255
              num_of_pros=$(grep -c ^processor /proc/cpuinfo)
              go test ./... -race -cover -p "$num_of_pros"
              popd > /dev/null 2>&1 || exit 255
          done
